### ISSUE TITLE
Why not allow multiple webmention endpoints?

### ISSUE THREAD

**Issue by kevinmarks** [aaronpk/webmention#13]
Currently the spec says:

>The webmention endpoint is advertised in the HTTP Link header or a `<link>` or `<a>` element with `rel="webmention"` . If more than one of these is present, the HTTP Link header takes precedence, followed by the `<link>` element, and finally the `<a>` element. Clients MUST support all three options and fall back in this order.

However it does not address what should be done if multiple endpoints are indicated for a page using one of these techniques.

I'd suggest that in this case, sending a webmention to each one found makes sense. As webmention does not define what endpoints should do, it is clear that there could be different webmention triggered services - one that creates useful comment threading, and one that caches linked-from pages, for example.

In addition, if you are migrating from one webmention service to another, being able to [ping both](http://indiewebcamp.com/irc/2015-11-28/line/1448701528335) in parallel is best practice to ensure consistency.

**Comment by rhiaro** [comment]
That seems like a useful thing to concretize in the spec.

**Comment by dissolve** [comment]
I think it makes a lot of sense to not allow multiple endpoints.  Its trivially easy to set up an endpoint that just repeats the message to any number of endpoints you need and it takes the requirement off of webmention senders of possibly sending numerous webmentions.  If someone starts to go a bit crazy and has 10 endpoints, we require the  WM sender to send 10 POSTs?  If any one implementation of a sender doesn't send to all you could miss mentions quite easily.

**Comment by sandhawke** [comment]
I don't care much either way, but agree this should be clarified in the spec.   I lean slightly toward agreeing with @dissolve.  

One related concept is the idea of adding a type parameter to the rel=webmention  (headers and elements) to provide con-neg without an additional round-trip.   In this case, the client would look through the links for one which had a type it understood/preferred.

**Comment by gobengo** [comment]
Allow mutiple

**Comment by aaronpk** [comment]
Clarify only the first endpoint should be used: https://indiewebcamp.com/wiki/index.php?title=Webmention&diff=23674&oldid=23673

I also added an FAQ based on what we discussed at the F2F meeting: https://indiewebcamp.com/Webmention-faq#What_if_multiple_webmention_endpoints_are_discovered

Does this cover it for everyone here?

**Comment by aaronpk** [comment]
Closing this as complete based on [today's call](https://www.w3.org/wiki/Socialwg/2015-12-08-minutes#Summary_of_Resolutions)

**Comment by aaronpk** [comment]
Marking as commenter satisfied based on his +1 in the minutes https://www.w3.org/wiki/Socialwg/2015-12-08-minutes
