### ISSUE TITLE
What constitutes the idea of source 'linking to' target?

### ISSUE THREAD

**Issue by csarven** [aaronpk/webmention#17]
The intention of this issue is to clarify the following in the current spec in order to give insight into other issues.

> The receiver SHOULD perform a HTTP GET request on source to confirm that it actually links to target (note that the receiver will need to check the Content-type of the entity returned by source to make sure it is a textual response).

Two simplified examples at source `http://example.org/foo`:

1. `<a href="http://example.org/bar">`:

    a. If the endpoint receives `http://example.org/bar`, there is a match.
    b. If it receives a different value, there is no match, but may want to process further at its own discretion.
    c. If it receives no value, receiver has to make a decision on what may be of interest at source.

2. `<a href="http://t.co/abc">` (a short URL or any URL which may or may not eventually resolve at one of target's URLs):

    a. If the endpoint receives `http://t.co/abc`, there is a match.
    b. If it receives a different value, there is no match, but may want to process further at its own discretion.
    c. If it receives no value, receiver makes a decision on what may be of interest at source.

Options b and c are similar. I've intentionally kept them distinct to have a clear discussion. The intention here is not to necessarily lay down how verifications should be conducted but to understand the moving components better.

Note: This issue emerged from issue #16 . It may also reflect and incorporate the output of issue #1 , #5 , and #12 . See also proposed [possible POSTs with interpretations](http://csarven.ca/webmention#webmention-posts).

**Comment by sandhawke** [comment]
Not sure this is the place, but can we agree `<a href="http://example.org/bar">http://example.org/foo</a>` is NOT linking to `http://example.org/foo`?     There are a bunch of other test cases involving relative URI resolution, HTML entities, punycode, etc, as well.    It may be we need separate notions on the sender and endpoint, too.  That is, a module that is doing webmentions for a document MUST process certain things as links, and MAY process others.   Meanwhile, an endpoint MUST reject certain things as links, and MAY reject others.    Those two "MUST" sets might be different.

**Comment by csarven** [comment]
@sandhawke For anything from the HTML/XML families - I agree that /foo is not being linked to. It is just some text content. For text/plain or binary types, it is a _mention_.

**Comment by aaronpk** [comment]
Clarified that the source document must have an exact match of the target URL https://indiewebcamp.com/Webmention#Verification 

Does this clarify it enough?

**Comment by aaronpk** [comment]
Closing this as complete based on [today's call](https://www.w3.org/wiki/Socialwg/2015-12-08-minutes#Summary_of_Resolutions)

**Comment by aaronpk** [comment]
This has been incorporated into the spec, and the group approved the change in December. @csarven I hope this addresses your concerns, but if not, feel free to reopen the issue with clarifying information.
