### ISSUE TITLE
Security consideration: Attacker can cause webmention sender to send arbitrary requests to victim

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/webmention#20]
Assumptions:
* The victim is a server that processes query string parameters the same way as post body parameters (many web frameworks allow code to access these parameters the same way, so this is actually relatively common, e.g. PHP's `$_REQUEST` or Ruby (Sinatra)'s `params[:foo]`)
* The server performs some action that the attacker, Chuck, normally can't do from his own server (e.g. a form with no authentication that lives behind a firewall, or an endpoint that uses an IP address as authentication)
* Alice has a blog that lives on a server that can trigger this action on the victim server
* Alice's blog supports Salmentions (e.g. sending a webmention to previous commenters when a new comment is received), or an alternate attack involves socially engineering Alice to write a post that links to Chuck's malicious URL

The attacker, Chuck, creates a reply to one of Alice's blog posts at http://chuck.example.com/attack and sets the webmention endpoint for the page to the victim's URL, which may be behind a corporate firewall. The URL contains query string parameters that are crafted to cause the victim to perform some operation such as creating a new user account, or some other undesirable operation. An example might be an internal user registration form that creates accounts that can be used from outside the firewall. For example, Chuck sets the webmention endpoint to `http://victim.internal/register?userid=chuck&password=1234`.

Once Chuck has set the webmention endpoint on his page to the internal server, he then sends a webmention to one of Alice's blog posts that is running on a blog inside the firewall at http://alice.internal/post/100. This causes Alice's server to fetch his reply and show it as a comment.

Chuck then sends a follow-up comment which Alice's server accepts. Then, following the Salmention rules, Alice's server sends webmentions to all previous comments to notify them of the new comment.

Alice's server discovers the maliciously crafted webmention endpoint on Chuck's original comment, and sends a post request to it that looks like the following:

```
POST /register?userid=chuck&password=1234 HTTP/1.1
Host: victim.internal
Content-type: application/x-www-form-encoded

source=http://alice.internal/post/100&target=http://chuck.example.com/attack
```

The vulnerable server ignores the source and target parameters but processes the query string parameters as if they were post values. 

The summary is that the attacker can cause Alice's server to send arbitrary requests to a server.

---

* Is this something worth addressing or acknowledging in the spec? 
* Are there too many preconditions for this attack to be worth noting?
* Is this really any different from getting Alice to visit a page in her browser that has javascript that submits a carefully crafted html form?

**Comment by aaronpk** [comment]
Potential solutions:

* Require the webmention endpoint be on the same domain as the page that advertises the endpoint
* Have a "pre-check" step where the sender first queries the endpoint to determine if it supports webmention, e.g. making an OPTIONS or HEAD request and looking for a specific header

**Comment by aaronpk** [comment]
Mitigation techniques:
* Limit the internal access of installed software on an internal network
* Add CSRF or authentication to internal endpoints that may be accepting post requests from internal servers

**Comment by kevinmarks** [comment]
I had a buggy implementation that sent `source` and `target` as query string parameters instead of form-encoded, and all the webmention endpoints I tried rejected them.
Is there a case for stripping query parameters  in the protocol step?

**Comment by aaronpk** [comment]
@kevinmarks that's a separate issue, and worth documenting. Currently the Wordpress webmention extension uses a query string as its webmention endpoint: `http://example.com/?webmention=endpoint` so it's not a good idea to require senders strip query string parameters of the webmention endpoint.

**Comment by gobengo** [comment]
I think I filed #22 as one way of solving this.

**Comment by aaronpk** [comment]
#22 is a totally separate issue, I don't see how it relates to this.

**Comment by gobengo** [comment]
@aaronpk If the victim's robots.txt (or similar) said "Don't send things here", and the webmention sender was supposed to check that first, then the victim has a way of fighting this attack.

It's imperfect.

**Comment by aaronpk** [comment]
Okay yeah. I still think robots.txt is not a sufficient solution to solving this, and that a better way of handling this issue is to document it as a security consideration.

**Comment by aaronpk** [comment]
Upon re-reviewing this, I'm not even sure it deserves to have a mention in the security considerations section. Reviewing the list of assumptions necessary for this attack to even take place, it seems like a rather large set of requirements before this is a problem. It's also more a vulnerability of unrelated systems, since the mitigation techniques described are all things that have to be done on an external system. To summarize the recommendations the consideration section would make, a system should:

* prevent CSRF attacks
* prevent query string parameters from being used to send data in POST requests
* take appropriate precautions to limit access to systems on an internal network

These things seem like basic practices any application should be following, and aren't particularly unique to Webmention.

I believe @sandhawke was the one to originally raise this, so I would like his feedback before I close this.

**Comment by ePirat** [comment]
> These things seem like basic practices any application should be following, and aren't particularly unique to Webmention.

I agree to this but still think there should be some sort of verification in place to prevent servers to send POST requests to an arbitrary server the attacker specifies.

One of the solutions you proposed

> Require the webmention endpoint be on the same domain as the page that advertises the endpoint

will not work, I think, as it would prevent webmention services to work (which are not located on the same domain in most cases).
I think your proposal for a verification step would be a good solution:

> Have a "pre-check" step where the sender first queries the endpoint to determine if it supports webmention, e.g. making an OPTIONS or HEAD request and looking for a specific header

(Should only be required if that webmention endpoint is located on a different domain, though)

**Comment by aaronpk** [comment]
@sandhawke I haven't been able to find any docs on how HTML5 handles this. Do you happen to know if I'm just not looking in the right place? I was expecting to find something in the [embedded content](https://www.w3.org/TR/html5/embedded-content-0.html). There's an MDN article on [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) but it also doesn't really have anything I could use. Any other suggestions?

**Comment by cwebber** [comment]
To reiterate what I said at the F2F my main worry is about localhost.  I think even GET requests to localhost could be potentially dangerous given how many processes assume that localhost-only access is a fairly lax-security option.  I think the F2F discussed option of mentioning that localhost access must not be permitted would easily solve this though.

**Comment by aaronpk** [comment]
@cwebber yeah I already added a section about localhost. (I don't think I pushed it to github yet tho)

**Comment by aaronpk** [comment]
From what I can tell, HTML does not list any security considerations for loading external resources. The spec even says that a user agent MUST load external resources specified in a `<link>` tag. https://www.w3.org/TR/2008/WD-html5-20080610/single-page/#href1

I would like to propose closing this issue given that the main concern about potentially accessing localhost resources has been addressed. See the following URL for the text added: http://webmention.net/draft/#avoid-sending-webmentions-to-localhost

**Comment by ePirat** [comment]
Well, while I agree that HTML loads external resources, this is just about GET requests. A browser will never load external resources with a POST request, as POST in most cases causes some action to happen and data to change and therefore allows for far more abuse than GET requests do.

**Comment by aaronpk** [comment]
We discussed this during the [March 16 telcon](https://www.w3.org/wiki/Socialwg/2016-03-29-minutes). The conclusion we came to was that it's essentially the same thing as allowing a browser to post a form cross-domain. 

The question then remains is this more similar to posting a form from Javascript, or posting a form from HTML. If the former, then we should use the same security mechanism used by HTML, namely [CORS](https://www.w3.org/TR/cors/).

If we need to make changes to support CORS headers, then it will basically look like the following:

## Webmention Receivers
* If a webmention endpoint receives webmentions for a different [origin](https://www.w3.org/Security/wiki/Same_Origin_Policy), (different scheme, host or port) than the endpoint itself, then it MUST respond to an HTTP OPTIONS request and include an HTTP header in the response with an [Access-Control-Allow-Origin header](https://www.w3.org/TR/cors/#access-control-allow-origin-response-header) listing the origins it accepts webmentions for, or `*` to allow any origin.

## Webmention Senders
* If the sender discovers the endpoint is a different origin than the target URL, then it MUST first make an HTTP OPTIONS request and check the value of the [Access-Control-Allow-Origin header](https://www.w3.org/TR/cors/#access-control-allow-origin-response-header). The sender MUST NOT proceed with the Webmention POST request unless the header includes the origin of the target URL or the string `*`.

**Comment by voxpelli** [comment]
Talked a bit about this on IRC and the term `SSRF` came up so just adding it here for reference: https://cwe.mitre.org/data/definitions/918.html

My view is that apart from maybe suggesting filtering out exotic port-numbers and protocols (as mentioned in the above link and as implemented by eg. WordPress [wp_http_validate_url()](https://developer.wordpress.org/reference/functions/wp_http_validate_url/)) then any threats against normal internal host names or similar would have to be dealt with by either:

1. Running the client in an environment with no access to such internal resources
2. Utilizes a proxy that proxies all potentially harmful URL:s to outside of the environment that has access to internal resources

**Comment by aaronpk** [comment]
Hm, I'm not a fan of disallowing port numbers in the webmention endpoint, but I could see adding language that requires the endpoint be either http or https scheme only.

Re: 1. in your suggestion, I think you meant running the _server_ in an environment with no access to internal resources. 

I like that idea, it puts the onus on the person installing the software to be aware of the environment they're installing it in. It means if someone installs software that sends webmentions on a machine that can access internal systems, they need to be aware that it's possible for someone to create a situation where that software sends POST requests to arbitrary servers. That sounds like something I can add to the security considerations section. 

Proposed language to add as a new security consideration:

# Limit access to protected resources

It is possible for an attacker to advertise a Webmention endpoint that points to an arbitrary URL. As such, if you install software that sends Webmentions on a server that is behind a firewall or otherwise has access to normally protected resources, you should be aware that an attacker can cause the server to send a POST request to an internal server. You SHOULD take precautions to ensure this server cannot access protected resources by either:

* run the client in an environment that does not have access to such internal resources
* proxy all HTTP requests from this sender through a proxy that blocks access to internal resources

How does this sound @ePirat and @sandhawke?

**Comment by tantek** [comment]
The proposed language to add as a new security consideration "Limit access to protected resources" makes sense to me and provides a good heads-up to such firewall situations that such users should be aware of in general (beyond Webmention).

+1 to adding "Limit access to protected resources" section and as sufficient to resolve and close this issue.

**Comment by aaronpk** [comment]
I've added in the proposed language, which addresses the issue as last discussed on the conference call [on 2016-03-29](https://www.w3.org/wiki/Socialwg/2016-03-29-minutes). If you feel like this does not fully address the issue, feel free to comment below.

**Comment by ePirat** [comment]
I still think that this should be addressed as you proposed in a [previous comment](https://github.com/aaronpk/webmention/issues/20#issuecomment-209385798). In my opinion it's still a problem that my server could be made to POST to "fake" webmention endpoints.

**Comment by aaronpk** [comment]
For the record, my initial description of the issue was incorrect. Salmention does not say "Then, following the Salmention rules, Alice's server sends webmentions to all previous comments to notify them of the new comment." Actually, Salmention says that you should re-sent any previously sent webmentions. This means you actually won't be in the situation of a commenter causing you to send a new webmention.

**Comment by ePirat** [comment]
Ok, thanks for clarifying. My concern is invalid then and my comment can be disregarded.

**Comment by mblaney** [comment]
I think there's enough mitigation 'built in' with the localhost check now, but after reading this issue and #15, it's worth clarifying that it's not a salmention problem. @sandhawke specified that Alice would be writing a reply post to the attacker, not that the attacker could force endpoint discovery via a comment.
