### ISSUE TITLE
Senders and Verifiers should respect robots.txt

### ISSUE THREAD

**Issue by gobengo** [aaronpk/webmention#22]
If an alleged webmention endpoint is blocked by robots.txt on that domain, senders should not send to it.
If a receiver is about to verify by requesting some endpoint, and that endpoint is blocked by robots.txt, the receiver should not request it. 
http://www.robotstxt.org/robotstxt.html

Is this a good idea?

**Comment by aaronpk** [comment]
robots.txt was originally designed for robots which crawl web pages ("recursively retrieving linked pages" [[1]](http://www.robotstxt.org/orig.html)). Because of this, it seems like it's not appropriate to use it in Webmention which is fetching specific URLs that are indicated to it.

**Comment by kevinmarks** [comment]
This is a MAY at most - could be worth referring to, as some fetch abstractions respect it by default.

**Comment by aaronpk** [comment]
Closing this based on [today's call](https://www.w3.org/wiki/Socialwg/2015-12-08-minutes#Summary_of_Resolutions)
