### ISSUE TITLE
Discuss handling of fragments in URLs

### ISSUE THREAD

**Issue by kevinmarks** [aaronpk/webmention#24]
As noted here: https://tinokremer.nl/2015/benwerd-i-figured-out-what-goes-wrong-with-webmentions-comments  
Webmention handlers should strip fragments before checking if the URL is one they handle. Fragments can be used to direct the webmention to a subsection of the destination URL, and if they are fragmentions, a particular phrase.

**Comment by aaronpk** [comment]
Is it worth noting explicitly that a webmention receiver shouldn't just naively use the full target URL to look up a matching post in its "database"? This isn't really a spec issue, it's more of an implementation detail.

Note that it's still required that if the target parameter includes a fragment, then that full URL including the fragment must appear at the source URL.

**Comment by aaronpk** [comment]
This has been incorporated into the latest draft.

**Comment by aaronpk** [comment]
@kevinmarks please let me know if the current text addresses your issue: http://webmention.net/draft/#request-verification
