### ISSUE TITLE
Should be source syntax agnostic

### ISSUE THREAD

**Issue by rhiaro** [aaronpk/webmention#25]
I thought the webmention spec was supposed to be agnostic of the markup used in the source. As such, a MUST on microformats2 parsing in 2.2.4 seems inappropriate. 

Even though supporting updating mentions is MAY, this implies that if you are going to support it, you have to support mf2, which may deter people who are interested in other kinds of semantic markup, or indeed syntaxes other than html, from supporting updating at all. If someone wants to support updates, shouldn't it be left up to them to decide how they're going to get the updated data? (Which would be consistent with other similar decisions left up to implementers elsewhere in the spec).

**Comment by aaronpk** [comment]
The intent was to require supporting updates this way if you are going to be parsing mf2 webmentions. The nesting of the clauses should indicate that.

**Comment by aaronpk** [comment]
If you read it closely, it says it "MUST support updating data from properties of the primary object of the source" (explicitly not requiring updates use mf2), it then goes on to say it "MAY support updating data from the h-entry", in which case it MUST follow the mf2 and h-entry specs.

http://webmention.net/draft/#updating-existing-webmentions

**Comment by rhiaro** [comment]
Hm, I didn't read it that way, but I see what you mean. In the interests of shortening/simplifying core spec content, I feel like these specifics belong better in implementation details?

**Comment by rhiaro** [comment]
Especially since they are MAY anyway

**Comment by aaronpk** [comment]
I am glad they are tucked under the "Update" section, but it's more than just an implementation detail. The point is that if someone is going to support updates of h-entrys, then we want to ensure they have a clear path to follow so that everyone does it the same way. Especially for example, having a normative requirement on the Salmention extension for those implementations that do support updates. (Of course Salmention is optional since it's nested under a MAY)

**Comment by rhiaro** [comment]
Isn't it redundant to say 'if an implementation supports [other spec] it MUST do it according to the [other spec]' ? I'd shorten to...

* If both the verification steps are successful, it should update any existing data it picked up from source for the existing webmention.
  * When a webmention implementation does support updating (AKA a "webmention update implementation"), it must support updating data from properties of the primary object of the source.
    * One way to retrieve properties to update is according to the [microformats2-parsing] and [h-entry] specifications.
  * A webmention update implementation may support updating data from children, or other descendant objects of the primary object (as described by the [Salmention] extension specification (AKA a "Salmention implementation")).

**Comment by aaronpk** [comment]
I've removed the bullet points that seem redundant.

**Comment by aaronpk** [comment]
@rhiaro Please review the updated text and let me know if that addresses your concerns: http://webmention.net/draft/#updating-existing-webmentions

**Comment by aaronpk** [comment]
confirmed in person
