### ISSUE TITLE
Suggestion: simplifying notification

### ISSUE THREAD

**Issue by kousu** [aaronpk/webmention#26]
Webmentions replaced XMLRPC with something RESTish, but they aren't fully RESTful because they still use indirection, by sending encoded sender=...&receiver=....

It would drastically cull the number of errors and be much more web happy if the protocol instead was:
1. Notification: sender GETs receiver, with X-Webmention: sender
2. Finding the mention: receiver GETs sender, parses microformats searching for any with a link to receiver

This mixes the GET/POST pair that sender does into a single GET, which will look totally normal to servers that don't understand, without requiring any HTML code changes. As more people come online to webmentions, servers can progressively start to adopt them, but until then nothing untoward happens if a notification is sent when no one is listening. The current spec does a sorta preflight check by asking the receiver if and where its webmentions should go.

Another idea is simply to use the Referer header in step 1, which I think is something at least some blog engines used to do for finding trackbacks: blogs would ride on the back of their surfers for tracing out the web.  But by just making the server pretend to be a surfer, you get immediate push notification.

I guess that having a separate webmention endpoint made deployment seem easier, especially to something like Wordpress. But it should be just as simple to write some middleware that catches X-Webmention headers. The longest part is what to do with the mention once you've got it, anyway.

**Comment by kousu** [comment]
Incidentally, I think this obviates #20.

**Comment by aaronpk** [comment]
This idea has come up before, but is ultimately a non-starter. http://indiewebcamp.com/Webmention-brainstorming#LINK_verb

The main problem is doing this would prevent Webmention from being deployed in many many circumstances. Not every hosting environment gives people the ability to see the headers or run code there. Static websites and websites on a CDN are the most obvious case. But also when you start looking at existing deployed systems (imagine large old forum software, or home-grown enterprise systems), it may not be possible or practical to modify them to handle webmentions, where adding an HTML tag to delegate to a separate webmention handler is easy.

I'm also not sure where the "RESTish" comes from. Webmention is definitely more of an RPC style protocol than anything attempting to resemble REST.

**Comment by kousu** [comment]
That's why I said middleware: if you're in WSGI you're right in the thick of that already. If you're on a plain site you can write an apache `mod_webmention`.

True, if you don't own the server you're stumped until if and when the CDNs and hosters decide they like these. What does a caching CDN do with POSTs? It must hit the backend server right? Would changing to a POST make notifications going through CDNs? I don't have a way to make the static-site-on-a-budget-hoster use case happy, except to say that if you've actually got a static site then how are the comments getting updated?

My personal UX is really bad when I need three layers of indirection and need to worry about reflection attacks. <link rel="me"> is awesome because it collects

**Comment by sandhawke** [comment]
Using the referer header is called refback, https://en.wikipedia.org/wiki/Refback .   I've always really liked it.

Do we have a standard name for the requirement that rules this out?  "static sites"?    "legacy sites?"   This might be the largest bifurcation point within the WG.    It would be nice to point to it whenever this comes up.

**Comment by aaronpk** [comment]
@sandhawke we really do need to give this requirement a name since it keeps coming up. It's not just "static sites" in the sense of cheap hosting and using hip new static site generators, and not just legacy sites. Anything deployed on a CDN is essentially a static site, since the backend code is only run infrequently. There are also cases in larger companies where the person/team responsible for deploying a site doesn't want to (or can't) also run infrastructure for handling webmentions, so having the indirection step allows that to be offloaded to a separate service.

**Comment by aaronpk** [comment]
@kousu Sadly using the Referer header is not going to work, since it's already known to be full of spam. I encourage you to try prototyping this on your site to start collecting Referer headers and you'll quickly see what I mean.

There are also already a number of people using webmention on static sites. There are two ways to do it, either have a Javascript snippet load the comments client-side, or regenerate the static HTML when a new comment is received. 

* https://indiewebcamp.com/Jekmentions
* https://webmention.herokuapp.com/

**Comment by kousu** [comment]
Well thanks for the explanation. That's too bad that refback won't work for that use case.  It would really well work for my use case (so long as I had working spam measures) because I can implement without needing the rest of the web to cooperate too much ("principles not protocols", right?). I'm definitely on the far side of that bifurcation.

I'll close this for now. Maybe reopen it if you want to brainstorm a name.

**Comment by aaronpk** [comment]
Cool. There's definitely something interesting to be done with analyzing all the Referer links you receive, I'm just not sure it's part of the Webmention spec. fwiw I'm also logging incoming Referers (as is everyone who runs web analytics software like Google Analytics and Webalyzer).
