### ISSUE TITLE
Register "webmention" with IANA

### ISSUE THREAD

**Issue by dret** [aaronpk/webmention#29]
seeing that http://www.iana.org/assignments/link-relations/link-relations.xhtml currently does not list "webmention" as a registered link relation type, i am proposing to add a section to the draft that registers "webmention" in the IANA registry according to RFC 5988. i'd be more than happy to contribute such a section. this should make it easier for people discovering "webmention" links on the web to find the authoritative document specifying the link relation type.

**Comment by kevinmarks** [comment]
The iana registry is being overhauled through rfc5988bis at the moment, so
awaiting the outcome of that process makes more sense.

**Comment by dret** [comment]
On 2016-01-13 10:33, Kevin Marks wrote:
> The iana registry is being overhauled through rfc5988bis at the moment, so
> awaiting the outcome of that process makes more sense.

what's the cost of adding to the existing registry (apart form adding a 
small appendix to the draft that i am volunteering to contribute)? it's 
unlikely that RFC 5988 will be replaced very soon. registering with the 
current registry and then adjusting when a new registry/process is in 
place may be the best way to make sure that things are in sync.

**Comment by aaronpk** [comment]
I don't have an issue if you want to add it to the registry. I don't know anything about the process so I wouldn't be much help, but if you submit a PR and manage the communications with iana that's fine with me.

**Comment by dret** [comment]
On 2016-01-13 10:54, Aaron Parecki wrote:
> I don't have an issue if you want to add it to the registry. I don't
> know anything about the process so I wouldn't be much help, but if you
> submit a PR and manage the communications with iana that's fine with me.

ok, thanks. it's a very simple process. basically, it's an appendix 
requesting registration, and then an email to the review list, which 
usually results in "looks good to us". after that, it will be added to 
the registry, linking to the spec as a reference.

here is one example for such an appendix: 
https://tools.ietf.org/html/rfc6892#section-4

i'll create a PR later today. thanks!

**Comment by dret** [comment]
first stab at https://github.com/aaronpk/webmention/pull/30; comments/feedback very welcome.

**Comment by aaronpk** [comment]
Thanks for this. It's incorporated into the latest Editor's Draft and will be published when the next Working Draft is published.

**Comment by dret** [comment]
On 2016-02-29 7:02 , Aaron Parecki wrote:
> Thanks for this. It's incorporated into the latest Editor's Draft and
> will be published when the next Working Draft is published.

sounds good. i will send a request to the IETF list when the draft has 
been published, and then it should be relatively easy to have it 
approved by the expert and added to the IANA registry.

**Comment by dret** [comment]
hello link-relations.

https://www.w3.org/TR/2016/WD-webmention-20160301/#iana-considerations 
defines a new link relation type that should be added to the IANA link 
relation registry. here is an excerpt with the link relation type 
description:

-------------------------------------


Relation Name: webmention

Description: Identifies a target URI that supports the Webmention 
protocol. This allows clients that mention a resource in some form of 
publishing process to contact that endpoint and inform it that this 
resource has been mentioned.

Reference: W3C Webmention Specification (http://www.w3.org/TR/webmention/)

Notes: This is a similar "Linkback" mechanism to the ones of Refback, 
Trackback, and Pingback. It uses a different protocol, though, and thus 
should be discoverable through its own link relation type.

-------------------------------------

if there are any concerns or questions about this link relations type, 
please let us know.

thanks a lot and cheers,

dret.

-- 
erik wilde | mailto:erik.wilde@dret.net |
            | http://dret.net/netdret    |
            | http://twitter.com/dret    |

**Comment by dret** [comment]
just sent the note to link relations email list, please see the previous comment.

**Comment by dret** [comment]
hello link-relations.

a while ago this was sent to link-relations for expert review and 
feedback. is there anything missing that would help to move this forward?

thanks and cheers,

dret.

On 2016-03-02 08:43, Erik Wilde wrote:
> hello link-relations.
>
> https://www.w3.org/TR/2016/WD-webmention-20160301/#iana-considerations
> defines a new link relation type that should be added to the IANA link
> relation registry. here is an excerpt with the link relation type
> description:
>
> -------------------------------------
>
>
> Relation Name: webmention
>
> Description: Identifies a target URI that supports the Webmention
> protocol. This allows clients that mention a resource in some form of
> publishing process to contact that endpoint and inform it that this
> resource has been mentioned.
>
> Reference: W3C Webmention Specification (http://www.w3.org/TR/webmention/)
>
> Notes: This is a similar "Linkback" mechanism to the ones of Refback,
> Trackback, and Pingback. It uses a different protocol, though, and thus
> should be discoverable through its own link relation type.
>
> -------------------------------------
>
> if there are any concerns or questions about this link relations type,
> please let us know.
>
> thanks a lot and cheers,
>
> dret.
>

-- 
erik wilde | mailto:erik.wilde@dret.net |
            | http://dret.net/netdret    |
            | http://twitter.com/dret    |

**Comment by dret** [comment]
looks like the request was approved (thanks @mnot) and the link relation will be added soon:

https://mailarchive.ietf.org/arch/msg/link-relations/S3IjEecszpSShGKkEmsTAV0hGHk

**Comment by dret** [comment]
just got the note that registration is complete and indeed, it shows up in the registry:

http://www.iana.org/assignments/link-relations/link-relations.xhtml

**Comment by aaronpk** [comment]
Awesome, thanks for taking care of this!
