### ISSUE TITLE
No document at http://www.w3.org/ns/webmention

### ISSUE THREAD

**Issue by melvincarvalho** [aaronpk/webmention#38]
There is no document at : 

http://www.w3.org/ns/webmention#

Describing the key terms used in webmention

Is there something intended to be there, or a pointer to draft text.  That would make it easier to review.

**Comment by sandhawke** [comment]
What do you mean?   Sure there is.   

(Just kidding.   I just moved it into place now.)

Feedback at https://github.com/rhiaro/wm-ns/issues

If someone wants to write a JSON-LD context, that could be nice.

**Comment by melvincarvalho** [comment]
Thanks!  

Is this also machine readable?

**Comment by rhiaro** [comment]
JSON-LD and turtle versions are done now, should be up this afternoon. PRs or issues welcome at https://github.com/rhiaro/wm-ns/ if I messed anything up

**Comment by akuckartz** [comment]
:smile:

**Comment by sandhawke** [comment]
```
$ curl -s -H'Accept: application/ld+json' https://www.w3.org/ns/webmention | head
{
  "@context": {
    "wm": "http://www.w3.org/ns/webmention#",
    "Webmention": "wm:Webmention",
    "source": {
      "@id": "wm:source",
      "@type": "@id"
    },
    "target": {
      "@id": "wm:target",
...
```

and

```
$ curl -s -H'Accept:text/turtle' https://www.w3.org/ns/webmention | head
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://www.w3.org/ns/webmention#> a <rdf:Property> ;
    rdfs:label "Webmention Terms" ;
    rdfs:comment "This is the vocabulary description for terms used by the Webmention protocol." .

<http://www.w3.org/ns/webmention#Webmention> a rdfs:Class ;
...
```

**Comment by aaronpk** [comment]
Great! Can I close this issue then?

**Comment by sandhawke** [comment]
Yeah, pretty clearly we did exactly what the commenter wanted.    I trust @melvincarvalho will correct me if I'm wrong....
