### ISSUE TITLE
Differentiate new class "proxy receiver" and how it differs from "receiver"

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/webmention#44]
There are currently two types of webmention receivers implemented. The simple receiver exists on a single domain and accepts webmentions for URLs at that domain or URLs that redirect to that domain (such as shortURLs or aliases). Proxy receivers accept webmentions for domains other than themselves. Examples of these include:

* https://webmention.io
* https://mention-tech.appspot.com
* https://webmention.herokuapp.com

Parts of the spec that apply differently to proxy receivers include:

* "Verifies that target is a valid resource for which the receiver accepts Webmentions"

Feel free to comment with other parts of the spec that differ for this class.

**Comment by sandhawke** [comment]
Is this just editorial?

**Comment by aaronpk** [comment]
There isn't enough of a reason to add another conformance class, but instead we will add a sentence to the end of the section "For example, some receivers may accept webmentions for multiple domains."

**Comment by aaronpk** [comment]
Added this sentence.
