### ISSUE TITLE
Webmention should use JSON-LD

### ISSUE THREAD

**Issue by sandhawke** [aaronpk/webmention#47]
I do not support this issue.   I'm just helping organize here, separating it from #39.

In #39 there seem to be several proposals considered:

OPTION 1.  Where Webmention currently uses form-encoding, it should instead use JSON-LD.   That is, Webmention receivers would be required to understand JSON-LD and **not required** to understand form-encoding.    This has a big problem: it would be a  [flag day change.](https://en.wikipedia.org/wiki/Flag_day_%28computing%29), which seems impossible in a decentralized system.
 
OPTION 2.  Webmention receivers should be required to understand **both** JSON-LD and form-encoding.   This has a medium-sized problem: it would make every Webmention receiver more complicated, since it would have to understand two syntaxes, not just one.

I leave it to someone who supports this issue to make the case.   Hopefully they can do it with a very simple use case that shows how someone would benefit from one of these OPTIONS being adopted.

My suggestions is that if someone wants to use JSON-LD with webmentions, they instead use one of the non-webmention solutions that works with JSON-LD, like Semantic Pingback, Solid Inbox, or ActivityPub.

**Comment by sandhawke** [comment]
Closing, since I opened this as a home for a thread that didn't materialize.

Lots of email sort of on this topic.

**Comment by akuckartz** [comment]
No objections to closing this issue. Depending on the outcome of the mailing list discussion it can be reopened.
