### ISSUE TITLE
Consider expanding verification step 2

### ISSUE THREAD

**Issue by azaroth42** [aaronpk/webmention#5]
The discovery step is very clearly described, and allows for non-HTML content to participate using the protocol via HTTP Link headers.  The verification step, where the source is retrieved and it is confirmed that it links to the target, is less clear as to what constitutes a valid link.  Further processing requirements would be valuable here. 

As a strawperson:

* Check if any of the Link headers have the target as the IRI
* If the content-type of the delivered representation is (X)HTML, check for linking elements including link, a, img, object and so forth
* If the content-type is JSON or JSON-LD, check all of the values of they keys
* If the content-type is any other text, check as a string search in the entity-body
* Other content-types to be handled at the implementer's discretion

**Comment by aaronpk** [comment]
Thanks for this. I expanded the verification section to incorporate these changes. Does this address your concerns? https://indiewebcamp.com/Webmention#Verification

**Comment by aaronpk** [comment]
Closing this as complete based on [today's call](https://www.w3.org/wiki/Socialwg/2015-12-08-minutes#Summary_of_Resolutions)

**Comment by aaronpk** [comment]
@azaroth42 I didn't see your +1 in the minutes of this call, so just wanted to make sure your issue is addressed. Please comment here, thanks!
