### ISSUE TITLE
Move everything from Testing down to a Note

### ISSUE THREAD

**Issue by azaroth42** [aaronpk/webmention#7]
The content that follows "How to test webmentions" is implementation rather than specification focused, and would be great to keep, just in a Note or other mechanism than a spec :)

**Comment by aaronpk** [comment]
Agreed. I will do this as part of the conversion to respec.

**Comment by aaronpk** [comment]
This is done now, thanks!

**Comment by aaronpk** [comment]
@azaroth42 Please let me know here if this addresses your issue. The specific sections you are talking about have been marked as "non-normative," e.g. https://www.w3.org/TR/webmention/#extensions
